# Generated by Django 3.2.7 on 2022-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('local', models.IntegerField(blank=True, max_length=50, null=True)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
