# Generated by Django 3.2.7 on 2022-09-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
