# Generated by Django 3.2.7 on 2022-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamapp', '0002_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locals', models.CharField(max_length=50)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
